resources:
 repositories:
   - repository: 'ZAPTest'
     type: git
     name: 'ZAPTest'
     ref: refs/heads/master

trigger: none

stages:
  - stage: 'buildstage'
    jobs:
    - job: 'buildjob'
      pool:
       vmImage: 'ubuntu-latest'
      steps:
        - checkout: self
        - checkout: ZAPTest

        - bash: docker run -d -p <container_port>:<target_port> <your_image>
          displayName: 'App Container'
        - bash: |
               chmod -R 777  ./
               docker run --rm -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):<container_port> -x xml_report.xml
               true
          displayName: 'Owasp Container Scan' 
        - powershell: |
          $XslPath = 'ZAPTest/xml_to_nunit.xslt' 
          $XmlInputPath = 'xml_report.xml'
          $XmlOutputPath = 'converted_report.xml'
          $XslTransform = New-Object System.Xml.Xsl.XslCompiledTransform
          $XslTransform.Load($XslPath)
          $XslTransform.Transform($XmlInputPath, $XmlOutputPath)
   displayName: 'PowerShell Script'

       - task: PublishTestResults@2
         displayName: 'Publish Test Results'
         inputs:
         testResultsFormat: NUnit
         testResultsFiles: 'converted_report.xml'
